// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/3/2025, 3:57:58 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Acer/Desktop/SeatSystem/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/SeatSystem/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/SeatSystem/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/SeatSystem/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/SeatSystem/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Acer/Desktop/SeatSystem/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Acer/Desktop/SeatSystem/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Acer/Desktop/SeatSystem/frontend/pages/admin/buildingManage.vue","C:/Users/Acer/Desktop/SeatSystem/frontend/pages/admin/userManage.vue","C:/Users/Acer/Desktop/SeatSystem/frontend/pages/booking.vue","C:/Users/Acer/Desktop/SeatSystem/frontend/pages/history.vue","C:/Users/Acer/Desktop/SeatSystem/frontend/pages/index.vue","C:/Users/Acer/Desktop/SeatSystem/frontend/pages/login.vue","C:/Users/Acer/Desktop/SeatSystem/frontend/pages/profile.vue","C:/Users/Acer/Desktop/SeatSystem/frontend/pages/register.vue","C:/Users/Acer/Desktop/SeatSystem/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/SeatSystem/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/SeatSystem/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;