// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/16/2026, 10:20:43 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Acer/Desktop/BleakFuture/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/BleakFuture/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/BleakFuture/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/BleakFuture/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/BleakFuture/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Acer/Desktop/BleakFuture/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Acer/Desktop/BleakFuture/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Acer/Desktop/BleakFuture/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/BleakFuture/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/BleakFuture/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Acer/Desktop/BleakFuture/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;